# 1- Preprocessing

## Open the file

In [29]:
import pandas as pd
import numpy as np

pd.read_csv("hw_data.csv")

Unnamed: 0  Age  Gender Education Level   Income Marital Status  \
0             0  500  Female             NaN  31158.0            NaN   
1             1   73  Female         College  54465.0            NaN   
2             2   68    Male     High School  37427.0        married   
3             3   61  Female         College  52210.0        widowed   
4             4   34  Female         College  59325.0      separated   
..          ...  ...     ...             ...      ...            ...   
105          56   85  Female      University  39063.0       divorced   
106           0  500  Female             NaN  31158.0            NaN   
107          73   39  Female         College  55750.0        married   
108          28   80  Female     High School  32142.0      separated   
109          30  500  Female     High School  18442.0      separated   

     Employment Status Product Category  Satisfaction Level  Debt Status  
0                  NaN              NaN                   9            1  
1                  0.0                E                   5            1  
2                  0.0                D                   1            1  
3                  0.0                G                   8            1  
4                  1.0                A                   5            0  
..                 ...              ...                 ...          ...  
105                NaN                F                   8            0  
106                NaN              NaN                   9            0  
107                1.0                F                   5            1  
108                NaN                C                   7            1  
109                1.0                A                   3            0  

[110 rows x 10 columns]

## Examine file

In [30]:
df = pd.read_csv("hw_data.csv")

## Define missing values

In [31]:
missing_values = df.isnull()
missing_values

Unnamed: 0    Age  Gender  Education Level  Income  Marital Status  \
0         False  False   False             True   False            True   
1         False  False   False            False   False            True   
2         False  False   False            False   False           False   
3         False  False   False            False   False           False   
4         False  False   False            False   False           False   
..          ...    ...     ...              ...     ...             ...   
105       False  False   False            False   False           False   
106       False  False   False             True   False            True   
107       False  False   False            False   False           False   
108       False  False   False            False   False           False   
109       False  False   False            False   False           False   

     Employment Status  Product Category  Satisfaction Level  Debt Status  
0                 True              True               False        False  
1                False             False               False        False  
2                False             False               False        False  
3                False             False               False        False  
4                False             False               False        False  
..                 ...               ...                 ...          ...  
105               True             False               False        False  
106               True              True               False        False  
107              False             False               False        False  
108               True             False               False        False  
109              False             False               False        False  

[110 rows x 10 columns]

# Find outliers

In [55]:
def find_column_outliers(df, column_name):
    column = df[column_name]
    Q1 = np.quantile(column, 0.25)
    Q3 = np.quantile(column, 0.75)
    IQR = Q3 - Q1
    lower_limit = Q1 - (1.5 * IQR)
    upper_limit = Q3 + (1.5 * IQR)
    
    outliers = column[(column < lower_limit) | (column > upper_limit)]
    return outliers


## Decide about missing values (fill or drop)

In [32]:
missing_values_count = df.isnull().sum()
missing_values_count

Unnamed: 0             0
Age                    0
Gender                 0
Education Level       17
Income                12
Marital Status        19
Employment Status     35
Product Category      13
Satisfaction Level     0
Debt Status            0
dtype: int64

In [33]:
df.dropna()

Unnamed: 0  Age  Gender Education Level       Income Marital Status  \
2             2   68    Male     High School      37427.0        married   
3             3   61  Female         College      52210.0        widowed   
4             4   34  Female         College      59325.0      separated   
5             5   10  Female      Elementary      31918.0      separated   
7             7   25  Female     High School      23691.0        widowed   
10           10  500  Female         College      31654.0  never married   
18           18    2  Female      Elementary      43806.0        married   
20           20  500  Female      University      64165.0      separated   
24           24   25    Male     High School      27810.0       divorced   
25           25   67    Male     High School      46693.0        married   
30           30  500  Female     High School      18442.0      separated   
31           31   71    Male      University      37258.0  never married   
32           32   81  Female         College  314696218.0  never married   
34           34   92    Male     High School      26777.0      separated   
35           35   47  Female         College      36124.0        widowed   
37           37    0    Male      University      18335.0        widowed   
40           40  500  Female         College      45140.0        widowed   
50           50  500    Male      University  575772080.0        married   
51           51    0    Male         College      39728.0  never married   
54           54   33    Male     High School      34641.0  never married   
55           55   52    Male         College      53960.0       divorced   
59           59   90    Male         College  300245882.0        widowed   
60           60  500  Female         College      34060.0      separated   
62           62   21  Female      University      50701.0        married   
66           66   63  Female      Elementary      26442.0       divorced   
67           67   72  Female      University      31529.0        married   
69           69   33  Female      University      44423.0        widowed   
72           72   63    Male      University      42496.0        widowed   
73           73   39  Female         College      55750.0        married   
76           76    3  Female     High School      37208.0      separated   
77           77   99  Female      Elementary  286421460.0        widowed   
79           79   23  Female         College      44233.0        widowed   
80           80  500    Male      University      60010.0        married   
83           83   18  Female      Elementary      34445.0        married   
86           86   31  Female     High School  505250420.0      separated   
89           89   27  Female      University      49231.0        married   
91           91   52  Female     High School      41351.0       divorced   
94           94   49    Male         College      34922.0      separated   
96           96   24    Male         College      23286.0       divorced   
98           98   57  Female         College      23621.0        widowed   
101          86   31  Female     High School  505250420.0      separated   
103          59   90    Male         College  300245882.0        widowed   
107          73   39  Female         College      55750.0        married   
109          30  500  Female     High School      18442.0      separated   

     Employment Status Product Category  Satisfaction Level  Debt Status  
2                  0.0                D                   1            1  
3                  0.0                G                   8            1  
4                  1.0                A                   5            0  
5                  0.0                F                   3            1  
7                  0.0                A                   5            1  
10                 1.0                G                   7            0  
18                 0.0                C                   3

In [34]:
df.isna().sum()

Unnamed: 0             0
Age                    0
Gender                 0
Education Level       17
Income                12
Marital Status        19
Employment Status     35
Product Category      13
Satisfaction Level     0
Debt Status            0
dtype: int64

# Age

In [57]:
df['Age'].unique()

array([500,  73,  68,  61,  34,  10,  80,  25,  44,  89,  99,   7,  70,
        58,  76,  87,   2,  85,   9,  48,  67,   5,  92,  39,  71,  81,
        21,  47,   6,   0,  91,   1,  14,  40,  95,  50,  46,   8,  64,
        19,  33,  52,  20,  90,  45,  63,  72,  54,   3,  30,  23,  49,
        18,  94,  31,  88,  27,  93,  24,  57], dtype=int64)

In [56]:
outliers = find_column_outliers(df, "Age")

# print outliers
print(outliers)

0      500
10     500
20     500
30     500
40     500
50     500
60     500
70     500
80     500
90     500
106    500
109    500
Name: Age, dtype: int64


In [58]:
df = df.drop(outliers.index) #drop the all outliers

In [59]:
df['Age'].unique()

array([73, 68, 61, 34, 10, 80, 25, 44, 89, 99,  7, 70, 58, 76, 87,  2, 85,
        9, 48, 67,  5, 92, 39, 71, 81, 21, 47,  6,  0, 91,  1, 14, 40, 95,
       50, 46,  8, 64, 19, 33, 52, 20, 90, 45, 63, 72, 54,  3, 30, 23, 49,
       18, 94, 31, 88, 27, 93, 24, 57], dtype=int64)

# Education Level

In [35]:
df['Education Level'].value_counts()

Education Level
University     30
High School    28
College        19
Elementary     16
Name: count, dtype: int64

In [36]:
df['Education Level'].unique()

array([nan, 'College', 'High School', 'Elementary', 'University'],
      dtype=object)

In [37]:
df['Education Level'].fillna('Unknown', inplace=True)

C:\Users\CC\AppData\Local\Temp\ipykernel_14308\2888109952.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Education Level'].fillna('Unknown', inplace=True)


In [38]:
df['Education Level'].unique() # This column has been filled with "Unknown"

array(['Unknown', 'College', 'High School', 'Elementary', 'University'],
      dtype=object)

# Income 

In [39]:
df['Income'].unique()

array([3.11580000e+04, 5.44650000e+04, 3.74270000e+04, 5.22100000e+04,
       5.93250000e+04, 3.19180000e+04, 3.60150000e+04, 2.36910000e+04,
       4.81260000e+04, 4.28500000e+04, 3.16540000e+04, 6.74000000e+03,
       3.20050000e+04, 3.96970000e+04, 8.63305114e+08,            nan,
       1.41060000e+04, 4.28250000e+04, 4.38060000e+04, 2.37590000e+04,
       6.41650000e+04, 1.08450000e+04, 1.95144049e+08, 2.78100000e+04,
       4.66930000e+04, 3.83420000e+04, 3.81020000e+04, 3.21420000e+04,
       1.84420000e+04, 3.72580000e+04, 3.14696218e+08, 1.67550000e+04,
       2.67770000e+04, 3.61240000e+04, 1.83350000e+04, 6.47300000e+04,
       2.60030000e+04, 4.51400000e+04, 8.62386254e+08, 2.33410000e+04,
       3.20960000e+04, 4.89880000e+04, 3.46650000e+04, 2.53080000e+04,
       2.09050000e+04, 4.73960000e+04, 5.75772080e+08, 3.97280000e+04,
       4.47310000e+04, 3.24880000e+04, 3.46410000e+04, 5.39600000e+04,
       3.90630000e+04, 1.66470000e+04, 3.00245882e+08, 3.40600000e+04,
      

In [17]:
df['Income'].value_counts()

Income
5.752785e+07    12
3.115800e+04     2
5.575000e+04     2
3.214200e+04     2
1.844200e+04     2
                ..
3.146962e+08     1
3.725800e+04     1
3.810200e+04     1
3.834200e+04     1
3.600900e+04     1
Name: count, Length: 90, dtype: int64

In [40]:
income_mean = df['Income'].mean()
df['Income'].fillna(income_mean, inplace=True)  #Filled with mean

C:\Users\CC\AppData\Local\Temp\ipykernel_14308\413427636.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Income'].fillna(income_mean, inplace=True)


In [41]:
df['Income']

0      31158.0
1      54465.0
2      37427.0
3      52210.0
4      59325.0
        ...   
105    39063.0
106    31158.0
107    55750.0
108    32142.0
109    18442.0
Name: Income, Length: 110, dtype: float64

In [42]:
df['Income'].unique()

array([3.11580000e+04, 5.44650000e+04, 3.74270000e+04, 5.22100000e+04,
       5.93250000e+04, 3.19180000e+04, 3.60150000e+04, 2.36910000e+04,
       4.81260000e+04, 4.28500000e+04, 3.16540000e+04, 6.74000000e+03,
       3.20050000e+04, 3.96970000e+04, 8.63305114e+08, 5.75278452e+07,
       1.41060000e+04, 4.28250000e+04, 4.38060000e+04, 2.37590000e+04,
       6.41650000e+04, 1.08450000e+04, 1.95144049e+08, 2.78100000e+04,
       4.66930000e+04, 3.83420000e+04, 3.81020000e+04, 3.21420000e+04,
       1.84420000e+04, 3.72580000e+04, 3.14696218e+08, 1.67550000e+04,
       2.67770000e+04, 3.61240000e+04, 1.83350000e+04, 6.47300000e+04,
       2.60030000e+04, 4.51400000e+04, 8.62386254e+08, 2.33410000e+04,
       3.20960000e+04, 4.89880000e+04, 3.46650000e+04, 2.53080000e+04,
       2.09050000e+04, 4.73960000e+04, 5.75772080e+08, 3.97280000e+04,
       4.47310000e+04, 3.24880000e+04, 3.46410000e+04, 5.39600000e+04,
       3.90630000e+04, 1.66470000e+04, 3.00245882e+08, 3.40600000e+04,
      

In [49]:
df['Income'] = df['Income'].apply(lambda x: '{:,.2f}'.format(x))

In [65]:
df['Income']

1      54,465.00
2      37,427.00
3      52,210.00
4      59,325.00
5      31,918.00
         ...    
102    64,730.00
104    45,571.00
105    39,063.00
107    55,750.00
108    32,142.00
Name: Income, Length: 95, dtype: object

In [67]:
df['Income'] = df['Income'].str.replace(',', '').str.replace('.', '')


df['Income'] = df['Income'].astype(float)


df['Income'] = df['Income'] // 100  

In [68]:
df['Income']

1      54465.0
2      37427.0
3      52210.0
4      59325.0
5      31918.0
        ...   
102    64730.0
104    45571.0
105    39063.0
107    55750.0
108    32142.0
Name: Income, Length: 95, dtype: float64

# Marital Status


In [18]:
df['Marital Status'].value_counts()

Marital Status
separated        25
married          23
widowed          21
divorced         12
never married    10
Name: count, dtype: int64

# Employment Status

In [43]:
df['Employment Status'].value_counts() #we can encdoed

Employment Status
1.0    43
0.0    32
Name: count, dtype: int64

In [44]:
df['Employment Status'].unique()

array([nan,  0.,  1.])

In [45]:
df['Employment Status'].isna().sum()

35

In [46]:
df['Employment Status']

0      NaN
1      0.0
2      0.0
3      0.0
4      1.0
      ... 
105    NaN
106    NaN
107    1.0
108    NaN
109    1.0
Name: Employment Status, Length: 110, dtype: float64

In [47]:
from sklearn.preprocessing import LabelEncoder          
lbe=LabelEncoder()
lbe.fit_transform(df["Employment Status"])

df['Employment Status_encoded']=lbe.fit_transform(df["Employment Status"])
df['Employment Status_encoded'] 

0      2
1      0
2      0
3      0
4      1
      ..
105    2
106    2
107    1
108    2
109    1
Name: Employment Status_encoded, Length: 110, dtype: int64

In [50]:
from sklearn.preprocessing import LabelEncoder          
lbe=LabelEncoder()
lbe.fit_transform(df["Employment Status"])

df['Employment Status Encoded']=lbe.fit_transform(df["Employment Status"])
df['Employment Status Encoded']

0      2
1      0
2      0
3      0
4      1
      ..
105    2
106    2
107    1
108    2
109    1
Name: Employment Status Encoded, Length: 110, dtype: int64

In [52]:
df.drop(columns=['Employment Status Encoded'], inplace=True)

In [53]:
df.describe()

Unnamed: 0         Age  Employment Status  Satisfaction Level  \
count  110.000000  110.000000          75.000000          110.000000   
mean    49.390909   98.027273           0.573333            4.527273   
std     28.794780  143.933500           0.497924            2.801406   
min      0.000000    0.000000           0.000000            0.000000   
25%     26.250000   30.250000           0.000000            2.000000   
50%     49.500000   54.000000           1.000000            5.000000   
75%     73.750000   84.000000           1.000000            7.000000   
max     99.000000  500.000000           1.000000            9.000000   

       Debt Status  Employment Status_encoded  
count   110.000000                 110.000000  
mean      0.463636                   1.027273  
std       0.500958                   0.783536  
min       0.000000                   0.000000  
25%       0.000000                   0.000000  
50%       0.000000                   1.000000  
75%       1.000000                   2.000000  
max       1.000000                   2.000000

In [54]:
df.head()

Unnamed: 0  Age  Gender Education Level     Income Marital Status  \
0           0  500  Female         Unknown  31,158.00            NaN   
1           1   73  Female         College  54,465.00            NaN   
2           2   68    Male     High School  37,427.00        married   
3           3   61  Female         College  52,210.00        widowed   
4           4   34  Female         College  59,325.00      separated   

   Employment Status Product Category  Satisfaction Level  Debt Status  \
0                NaN              NaN                   9            1   
1                0.0                E                   5            1   
2                0.0                D                   1            1   
3                0.0                G                   8            1   
4                1.0                A                   5            0   

   Employment Status_encoded  
0                          2  
1                          0  
2                          0  
3                          0  
4                          1

## Why did you fill missing values or if you have dropped, why did you do so? 

In [9]:
# I dropped the missing values. As we saw the table, we can't predict the values that its come from where and its come truly(espcially 'age'). Thats why i think the best option is
# dropping, if we want to fill it, i can easly say that we don't know how we the values logically to evaluate. Some colums has been filled mean and like 'Unknown' . One of them
# has been encoded.

## Find outliers if there are

In [ ]:
# I already fixed the outliers as you can see above.

## Decide what will you do with outliers

## Find duplicates, how many are there? Decide what will you do about that?

In [60]:
duplicates = df[df.duplicated()]
duplicates   #There are three dublicates in here. 

Unnamed: 0  Age  Gender Education Level          Income Marital Status  \
100          29   39    Male     High School   57,527,845.16            NaN   
101          86   31  Female     High School  505,250,420.00      separated   
103          59   90    Male         College  300,245,882.00        widowed   

     Employment Status Product Category  Satisfaction Level  Debt Status  \
100                1.0                B                   4            0   
101                1.0                G                   4            1   
103                0.0                C                   6            1   

     Employment Status_encoded  
100                          1  
101                          1  
103                          0

In [61]:
df.drop_duplicates(inplace=True)

## Explain why did you do that?

In [ ]:
# Because of the no connection with all duplicates, it has dropped.

# 2- Categorization

## Categorize satisfaction in 3 level and label them as 'Low', 'Moderate' and 'High'. Add a new column named 'Satisfaction Category' and store them there

#### ||| Low Satisfaction : (1-3) ||| Moderate Satisfaction : (4-7) ||| High Satisfaction : (8-10) |||

In [63]:
mask1=df['Satisfaction Level'].between(1,3)
mask2=df['Satisfaction Level'].between(4,7)
mask3=df['Satisfaction Level'].between(8,10)

df.loc[mask1, 'Satisfaction Category']='Low '
df.loc[mask2, 'Satisfaction Category']='Moderate '
df.loc[mask3, 'Satisfaction Category']='High '

In [64]:
df['Satisfaction Category'].head()

1    Moderate 
2         Low 
3        High 
4    Moderate 
5         Low 
Name: Satisfaction Category, dtype: object

## Categorize income in 3 level and label them as 'Low', 'Moderate' and 'High'. Add a new column named 'Income Category' and store them there

In [76]:

mask_1=df['Income'].between(0,25000.0)
mask_2=df['Income'].between(25001.0,50000.0)
mask_3=df['Income'].between(50001.0,75000.0)

df.loc[mask_1, 'Income Category']='Low'
df.loc[mask_2, 'Income Category']='Moderate'
df.loc[mask_3, 'Income Category']='High'

In [78]:
df['Income Category'].head()

1        High
2    Moderate
3        High
4        High
5    Moderate
Name: Income Category, dtype: object

# 3- Analyse

## Comparing using pivot tables

### Is there a relation between marital status and debt status?

In [79]:
marital_relation = pd.crosstab(index=df['Marital Status'], columns=df['Debt Status'], normalize='index')
marital_relation #I would say easyly 'yes'

Debt Status            0         1
Marital Status                    
divorced        0.416667  0.583333
married         0.523810  0.476190
never married   0.375000  0.625000
separated       0.550000  0.450000
widowed         0.631579  0.368421

### Is there a relation between income category and debt status?

In [80]:
income_relation = pd.crosstab(index=df['Income'], columns=df['Debt Status'], normalize='index')
income_relation

Debt Status    0    1
Income               
6740.0       0.0  1.0
7010.0       1.0  0.0
10845.0      0.0  1.0
14106.0      0.0  1.0
16647.0      0.0  1.0
...          ...  ...
314696218.0  0.0  1.0
505250420.0  0.0  1.0
777761952.0  1.0  0.0
862386254.0  1.0  0.0
863305114.0  0.0  1.0

[80 rows x 2 columns]

### Is there a relation between education level and satisfaction category?

In [81]:
education_satisfaction_relation = pd.crosstab(index=df['Education Level'], columns=df['Satisfaction Category'], normalize='index')
education_satisfaction_relation

Satisfaction Category     High       Low   Moderate 
Education Level                                     
College                0.230769  0.307692   0.461538
Elementary             0.000000  0.714286   0.285714
High School            0.238095  0.238095   0.523810
University             0.360000  0.160000   0.480000
Unknown                0.076923  0.461538   0.461538

### Is there a relation between employment status and satisfaction category?

In [82]:
employment_satisfaction_relation = pd.crosstab(index=df['Employment Status'], columns=df['Satisfaction Category'], normalize='index')
employment_satisfaction_relation 

Satisfaction Category     High       Low   Moderate 
Employment Status                                   
0.0                    0.200000  0.320000   0.480000
1.0                    0.151515  0.363636   0.484848

# 4- General Conclusion

- 

In [ ]:


#To better understand the relationship, further analysis such as statistical tests 
#or graphical representations can be performed, taking into account the context of the data and the analysis needs.

---

### Checklist

- [x]  start homework;
- [ ]  file open;
- [ ]  file examined;
- [ ]  missing values defined;
- [ ]  missing values are filled;
- [ ]  explanation for the possible causes of missing values;
- [ ]  an explanation of how the blanks are filled;
- [ ]  an explanation of how the blanks are filled;
- [ ]  finding outliers;
- [ ]  handling outliers;
- [ ]  duplicates showed;
- [ ]  duplicates deleted;
- [ ]  an explanation of which method is used to find and remove duplicates;
- [ ]  data is categorized;
- [ ]  an answer to the question " Is there a relation betweenmarital status and debt status?";
- [ ]  an answer to the question " Is there a relation between income category and debt status?";
- [ ]  an answer to the question " Is there a relation between education level and satisfaction category?";
- [ ]  an answer to the question " Is there a relation between employment status and satisfaction category?"
- [ ]  conclusions are present on each stage;
- [ ]  a general conclusion is made.

---