In [ ]:
################### A ##################

In [1]:
##### 1 #####
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

C:\Users\umut\AppData\Local\Temp\ipykernel_9624\2557590455.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
##### 2 #####
ratings_values = np.random.randint(1, 1000, (20,2))
ratings = pd.DataFrame(ratings_values, columns=["Price", "Quality"])
print(ratings_values)
print()
display(ratings)

[[632 984]
 [136 415]
 [658  44]
 [560 633]
 [ 14 982]
 [554 805]
 [889 198]
 [ 31 539]
 [110 560]
 [952 629]
 [667 976]
 [698 265]
 [759 937]
 [715 694]
 [249 674]
 [383 585]
 [937 250]
 [917 876]
 [688 463]
 [338 598]]



Price  Quality
0     632      984
1     136      415
2     658       44
3     560      633
4      14      982
5     554      805
6     889      198
7      31      539
8     110      560
9     952      629
10    667      976
11    698      265
12    759      937
13    715      694
14    249      674
15    383      585
16    937      250
17    917      876
18    688      463
19    338      598

In [3]:
#### 3 #####
price =  ratings["Price"]
quality = ratings["Quality"]


print('Price: ', price)
print('Quality: ', quality)


Price:  0     632
1     136
2     658
3     560
4      14
5     554
6     889
7      31
8     110
9     952
10    667
11    698
12    759
13    715
14    249
15    383
16    937
17    917
18    688
19    338
Name: Price, dtype: int32
Quality:  0     984
1     415
2      44
3     633
4     982
5     805
6     198
7     539
8     560
9     629
10    976
11    265
12    937
13    694
14    674
15    585
16    250
17    876
18    463
19    598
Name: Quality, dtype: int32


In [4]:
##### 4 #####
print(len(ratings))

20


In [5]:
#### 5 #####
print('The mean of the price ratings: ', price.mean()) 
print('The median of the price ratings', price.median()) 

print('The mean of the quality ratings: ', quality.mean()) 
print('The median of the quality ratings', quality.median()) 

The mean of the price ratings:  544.35
The median of the price ratings 645.0
The mean of the quality ratings:  605.35
The median of the quality ratings 613.5


In [6]:
##### 6 #####
mean_ratings = ratings.mean(axis=1).round().astype(int)
print(mean_ratings)

0     808
1     276
2     351
3     596
4     498
5     680
6     544
7     285
8     335
9     790
10    822
11    482
12    848
13    704
14    462
15    484
16    594
17    896
18    576
19    468
dtype: int32


In [7]:
##### 7 #####
new_ratings_values = np.column_stack((price, quality, mean_ratings))
print(new_ratings_values)
print(type(new_ratings_values))
print(new_ratings_values.shape)

[[632 984 808]
 [136 415 276]
 [658  44 351]
 [560 633 596]
 [ 14 982 498]
 [554 805 680]
 [889 198 544]
 [ 31 539 285]
 [110 560 335]
 [952 629 790]
 [667 976 822]
 [698 265 482]
 [759 937 848]
 [715 694 704]
 [249 674 462]
 [383 585 484]
 [937 250 594]
 [917 876 896]
 [688 463 576]
 [338 598 468]]
<class 'numpy.ndarray'>
(20, 3)


In [8]:
new_ratings = pd.DataFrame(new_ratings_values, columns=['Price', 'Quality', 'Average'])
display(new_ratings)

Price  Quality  Average
0     632      984      808
1     136      415      276
2     658       44      351
3     560      633      596
4      14      982      498
5     554      805      680
6     889      198      544
7      31      539      285
8     110      560      335
9     952      629      790
10    667      976      822
11    698      265      482
12    759      937      848
13    715      694      704
14    249      674      462
15    383      585      484
16    937      250      594
17    917      876      896
18    688      463      576
19    338      598      468

In [ ]:
#################### B ####################

In [9]:
#### 1 ####
def mae(target, predictions):
    
    return np.mean(np.abs(target-predictions))

In [10]:
#### 2 ####
target = np.random.binomial(n=1, p=0.6, size=100)
predictions = np.ones(100, dtype=int)

print(target)

print(predictions)

[0 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 1 1 1 1 1 0
 0 0 1 0 1 0 1 0 1 1 1 0 1 0 1 0 0 1 0 0 0 1 1 1 0 1 1 0 1 0 0 0 1 1 1 1 1
 0 0 0 1 1 0 1 1 1 1 1 1 0 1 0 1 0 1 0 1 0 0 1 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [11]:
#### 3 ####
mean_absolute_error =  mae(target, predictions)
mean_absolute_error

0.39

In [12]:
#### 4 ####
print(1-np.mean(target))

print(mean_absolute_error)

0.39
0.39


In [ ]:
################ C ################

In [13]:
#### 1 ####
def pythagorean_length(vector):
    return np.sqrt(np.dot(vector, vector))

In [14]:
#### 2 ####
a = np.array([3, 4])

pythagorean_length(a)


5.0

In [15]:
#### 3 ####
a = np.array([5, 6])
b = np.array([1, 3])

c =    np.sqrt(np.dot(a - b, a - b))
print('The distance between a and b is', c)

from scipy.spatial import distance
print('The distance between a and b should be', distance.euclidean(a, b))

The distance between a and b is 5.0
The distance between a and b should be 5.0


In [ ]:
########################## D ####################
## Unfortunately, I could not undeerstand this part and could not do it.