# NumPy Homework

# A

## 1) import numpy library with his usual alias!

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

C:\Users\jos_m\AppData\Local\Temp\ipykernel_21044\2557590455.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


## 2) Create a random matrix, which has 2 columns and 20 rows. With this we will then create a pandas DataFrame!

In [3]:
ratings_values = np.random.randint(1, 7, size=(20, 2))
ratings = pd.DataFrame(ratings_values, columns=['Price', 'Quality'])
print(ratings_values)
print(ratings)

[[6 1]
 [5 2]
 [1 5]
 [1 3]
 [3 4]
 [6 3]
 [5 3]
 [2 2]
 [5 4]
 [3 2]
 [2 2]
 [4 5]
 [5 2]
 [3 4]
 [6 4]
 [1 6]
 [3 1]
 [3 2]
 [6 3]
 [3 5]]
    Price  Quality
0       6        1
1       5        2
2       1        5
3       1        3
4       3        4
5       6        3
6       5        3
7       2        2
8       5        4
9       3        2
10      2        2
11      4        5
12      5        2
13      3        4
14      6        4
15      1        6
16      3        1
17      3        2
18      6        3
19      3        5


## 3) Create two vectors from the previous DataFrame. We will use the same values from the previous DataFrame which we already have been created. The first one contains the evaluations which show the customer satisfaction for the prices, and the second one contains for the quality. How big how good! We will then print the vectors.

##### Hint: pd.DataFrame['column_name'] gives us a Series from a DataFrame. We can use it with the same functions as DataFrames.

In [4]:
price = ratings['Price']
quality = ratings['Quality']


print('Price: ', price)
print('Quality: ', quality)


Price:  0     6
1     5
2     1
3     1
4     3
5     6
6     5
7     2
8     5
9     3
10    2
11    4
12    5
13    3
14    6
15    1
16    3
17    3
18    6
19    3
Name: Price, dtype: int32
Quality:  0     1
1     2
2     5
3     3
4     4
5     3
6     3
7     2
8     4
9     2
10    2
11    5
12    2
13    4
14    4
15    6
16    1
17    2
18    3
19    5
Name: Quality, dtype: int32


## 4) Find the total numbers of visitors.

In [5]:
total_visitors = ratings.shape[0]
print('Total number of visitors:', total_visitors)

Total number of visitors: 20


## 5) Find and print the average ratings for each column using numpy functions (we will find the mean and median values)

In [6]:
print('The mean of the price ratings: ', np.mean(price))
print('The median of the price ratings:', np.median(price))

print('The mean of the quality ratings: ', np.mean(quality))
print('The median of the quality ratings', np.median(quality))

The mean of the price ratings:  3.65
The median of the price ratings: 3.0
The mean of the quality ratings:  3.15
The median of the quality ratings 3.0


## 6) Create a new vector which is the average of the ratings of two columns, price and quality. We will name it as mean_ratings. It will show the average rating for each customer. Round elements of the array to the nearest integer.

In [7]:
mean_ratings = np.round((price + quality) / 2).astype(int)
print(mean_ratings)

0     4
1     4
2     3
3     2
4     4
5     4
6     4
7     2
8     4
9     2
10    2
11    4
12    4
13    4
14    5
15    4
16    2
17    2
18    4
19    4
dtype: int32


## 7) Create ratings_values matrix again with the all three vectors. Average ratings, which has just been calculated in the previous exercise, should be the third column of the new matrix. All values in the matrix should be integer! New matrix should have 20 rows and 3 columns!

In [8]:
new_ratings_values = np.column_stack((price, quality, mean_ratings))
print(new_ratings_values)
print(type(new_ratings_values))
print(new_ratings_values.shape)

[[6 1 4]
 [5 2 4]
 [1 5 3]
 [1 3 2]
 [3 4 4]
 [6 3 4]
 [5 3 4]
 [2 2 2]
 [5 4 4]
 [3 2 2]
 [2 2 2]
 [4 5 4]
 [5 2 4]
 [3 4 4]
 [6 4 5]
 [1 6 4]
 [3 1 2]
 [3 2 2]
 [6 3 4]
 [3 5 4]]
<class 'numpy.ndarray'>
(20, 3)


In [9]:
new_ratings = pd.DataFrame(new_ratings_values, columns=['Price', 'Quality', 'Average'])
display(new_ratings)

Price  Quality  Average
0       6        1        4
1       5        2        4
2       1        5        3
3       1        3        2
4       3        4        4
5       6        3        4
6       5        3        4
7       2        2        2
8       5        4        4
9       3        2        2
10      2        2        2
11      4        5        4
12      5        2        4
13      3        4        4
14      6        4        5
15      1        6        4
16      3        1        2
17      3        2        2
18      6        3        4
19      3        5        4

# B

## 1) Create *Mean Absolute Error (MAE)* function

\begin{equation}
MAE=\frac{1}{n}\sum_{i=1}^n|target_i - predictions_i|
\end{equation}

In [10]:
def mae(target, predictions):
    n = len(target)  # Gözlem sayısı
    absolute_errors = np.abs(target - predictions)  # Mutlak hatalar
    mean_absolute_error = np.mean(absolute_errors)  # Ortalama mutlak hata
    return mean_absolute_error

## 2) Create two arrays each of them has $100$ observations. We will use them for *target* and *predictions* labelling. The target array should consist only $0$ or $1$ values which are random created, while predictions only integer $1$. The target array should have a *binomial distribution* which gives $1$ with $60$% probability.

In [11]:
target = np.random.binomial(1, 0.6, size=100)
predictions = np.random.randint(1, 2, size=100)

print("target: ", target)
print()
print("predictions: ",predictions)

target:  [0 0 0 1 1 1 0 0 0 0 1 1 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 1 1 1 0 0 1 1 0 1 1
 0 0 1 0 1 1 1 0 1 0 1 1 0 0 0 1 1 1 1 1 0 1 1 1 0 0 1 0 1 1 0 0 0 1 1 1 0
 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 0 1 0 0 0 0 1 0 1 1 0]

predictions:  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## 3) Find the *MAE* with your mae function

In [12]:
mean_absolute_error = mae(target, predictions)
print('Mean Absolute Error:', mean_absolute_error)

Mean Absolute Error: 0.43


## 4)  Run the code in this step. Observe the printed outputs. Try to run the codes a few times from step 2. What do you think about the results? Give your thoughts shortly with 3 - 5 sentences about why two outputs are the same. What is your conclusion?

In [13]:
print(1-np.mean(target))

print(mean_absolute_error)

0.43000000000000005
0.43


 ### < 
The reason why the two values are close or the same is because the Mean Absolute Error (MAE) doesn't worry about whether the differences between actual values (target) and predicted values (predictions) are positive or negative. It just looks at how big the differences are on average. So, even if the numbers in target and predictions change each time we run the code, the average difference tends to stay similar. This shows that MAE is a good way to see how well a prediction model is working.>

## 5) We have always chosen $1$ in our predictions, but the actual values at the target have changed each time. How likely is it that we got it right each time, and what determines this?

 ### < 
Since we always choose 1 in our predictions, there are two possible outcomes: either we get it right or we get it wrong. The likelihood of getting it right each time depends on how often the actual values in the target match our prediction of 1. If the actual values are mostly 1, then we are likely to get it right more often. However, if the actual values are mostly 0, then we are unlikely to get it right very often. So, the likelihood of getting it right each time is determined by how closely our prediction matches the actual values in the target. >

# C

## 1) Create a Pythagorean function using *np.dot()* to calculate vector length

$$v = [x, y] ==> len_v = \sqrt{x^2+y^2}$$

In [14]:
def pythagorean_length(vector):
    return np.sqrt(np.dot(vector, vector))

## 2) Calculate the length of the given vector using your *pythagorean_length* function and check your result comparing with the given

In [15]:
a = np.array([3, 4])
length_a = pythagorean_length(a)
print('Length of vector a:', length_a)

Length of vector a: 5.0


## 3) Find the shortest distance (Euclidean distance) using *np.dot()* between the given two vectors and compare the results to check

In [16]:
a = np.array([5, 6])
b = np.array([1, 3])

distance_ab = np.sqrt(np.dot(a - b, a - b))
print('The distance between a and b is', distance_ab)

from scipy.spatial import distance
print('The distance between a and b should be', distance.euclidean(a, b))

The distance between a and b is 5.0
The distance between a and b should be 5.0


# D - Obfuscating Data

It is best to obfuscate data by multiplying the numerical features (they can be seen as the matrix $X$) by an invertible matrix $P$. 

$$
X' = X \times P
$$

Try to do that and check how the features' values will look like after the transformation. By the way, the invertible property is important here so make sure that $P$ is indeed invertible.

## 1) Protect customers' personal data. It is necessary to develop a data transformation algorithm that makes it difficult to recover personal information in case the data falls into the wrong hands. This is called data masking or data obfuscation. However, the data must be protected in such a way that the quality of the machine learning models does not suffer. You don't need to choose the best model, just prove that the algorithm works correctly.

In [17]:
# pd.DataFrame
columns = ['gender', 'age', 'salary', 'family_members']
data = np.array([np.random.choice([0, 1], size=1000), 
                 np.random.randint(18, 100, 1000), 
                 np.random.normal(25000, 5000, 1000).astype(int), 
                 np.random.randint(0, 10, 1000)
                ])

personal_data = pd.DataFrame(data.T, columns=columns)
display(personal_data.tail(10))

gender  age  salary  family_members
990       1   36   25406               4
991       1   95   28104               1
992       0   87   18282               0
993       1   56   34701               1
994       1   85   23316               9
995       1   77   21259               0
996       0   50   24251               1
997       1   91   28814               1
998       0   83   13305               5
999       0   21   21566               6

In [18]:
# < write your code here > 

np.random.seed(0)  # For reproducibility

In [28]:
# < write your code here > a rondom generated square matrix
P = np.random.rand(4, 4)
print(P)


[[0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918]
 [0.11827443 0.63992102 0.14335329 0.94466892]
 [0.52184832 0.41466194 0.26455561 0.77423369]]


**(Hint:** https://numpy.org/doc/stable/reference/random/generator.html **)**

In [29]:
 # < write your code here > This is our new crypted datas.
obfuscated_data = personal_data @ P


In [30]:
# < write your code here > 
print("Obfuscated Data:",obfuscated_data)

display(obfuscated_data.head())

Obfuscated Data:           0        1       2        3
0   2491.50 13245.17 2982.08 19535.01
1   2927.78 15613.49 3511.98 23029.26
2   4214.26 22384.81 5040.80 33009.23
3   2715.92 14577.92 3273.70 21510.32
4   3664.26 19661.54 4415.52 29011.06
..      ...      ...     ...      ...
995 2589.77 13666.45 3083.86 20143.69
996 2917.73 15559.10 3499.80 22948.97
997 3497.56 18512.66 4173.62 27292.36
998 1657.48  8582.55 1946.94 12637.48
999 2574.39 13819.81 3102.84 20393.77

[1000 rows x 4 columns]


0        1       2        3
0 2491.50 13245.17 2982.08 19535.01
1 2927.78 15613.49 3511.98 23029.26
2 4214.26 22384.81 5040.80 33009.23
3 2715.92 14577.92 3273.70 21510.32
4 3664.26 19661.54 4415.52 29011.06

## 2) Can you guess the customers' ages or income after the transformation?

In [31]:
# After the transformation, it's not possible to accurately guess the customers' ages or income. 


gender  age  salary  family_members
count    0.00 0.00    0.00            0.00
mean      NaN  NaN     NaN             NaN
std       NaN  NaN     NaN             NaN
min       NaN  NaN     NaN             NaN
25%       NaN  NaN     NaN             NaN
50%       NaN  NaN     NaN             NaN
75%       NaN  NaN     NaN             NaN
max       NaN  NaN     NaN             NaN

#### write your conlusion here

## 3) Can you recover the original data from $X'$ if you know $P$? Try to check that with calculations by moving $P$ from the right side of the formula above to the left one. The rules of matrix multiplication are helpful here.

In [33]:
# < write your code here >
# Secure Data
recovered_data = obfuscated_data @ np.linalg.inv(P)
pd.DataFrame(recovered_data, columns=columns).describe()

gender  age  salary  family_members
count    0.00 0.00    0.00            0.00
mean      NaN  NaN     NaN             NaN
std       NaN  NaN     NaN             NaN
min       NaN  NaN     NaN             NaN
25%       NaN  NaN     NaN             NaN
50%       NaN  NaN     NaN             NaN
75%       NaN  NaN     NaN             NaN
max       NaN  NaN     NaN             NaN

In [24]:
# Printing all three cases for a few customers


In [32]:
# Original Data
personal_data.tail(10)

gender  age  salary  family_members
990       1   36   25406               4
991       1   95   28104               1
992       0   87   18282               0
993       1   56   34701               1
994       1   85   23316               9
995       1   77   21259               0
996       0   50   24251               1
997       1   91   28814               1
998       0   83   13305               5
999       0   21   21566               6

In [26]:
# Secure Data
pd.DataFrame(personal_data).tail(10)  # < write your code here >

gender  age  salary  family_members
990       1   36   25406               4
991       1   95   28104               1
992       0   87   18282               0
993       1   56   34701               1
994       1   85   23316               9
995       1   77   21259               0
996       0   50   24251               1
997       1   91   28814               1
998       0   83   13305               5
999       0   21   21566               6

In [27]:
# Recovered Data
pd.set_option('display.float_format', '{:.2f}'.format)
recovered_dataframe = pd.DataFrame(recovered_data, columns=columns)
recovered_dataframe.tail(10)

gender  age  salary  family_members
990     NaN  NaN     NaN             NaN
991     NaN  NaN     NaN             NaN
992     NaN  NaN     NaN             NaN
993     NaN  NaN     NaN             NaN
994     NaN  NaN     NaN             NaN
995     NaN  NaN     NaN             NaN
996     NaN  NaN     NaN             NaN
997     NaN  NaN     NaN             NaN
998     NaN  NaN     NaN             NaN
999     NaN  NaN     NaN             NaN

#### write your conlusion here

---

# USEFUL INFORMATIONS

##### Matrices and Matrix Operations

- **A matrix** is a rectangular numeric table or two-dimensional array consisting of m rows and n columns.
- **A transpose of the matrix** is a matrix operation when its rows become columns with the same numbers.- **Dummy code** is a simple code that doesn't mean anything.
- **An identity matrix** is a square matrix with ones on the main diagonal and zeros elsewhere.
- **An inverse matrix** for a square matrix A is a matrix A with a superscript -1 whose product with A is equal to the identity matrix.
- **Invertible matrices** are matrices that have an inverse.
- **Non-invertible** are matrices that don't have an inverse.

# Properties of Matrices

Matrices have many properties in Linear Algebra.

<table>
<tr>
<td>Distributivity</td><td>$A(B+C)=AB+AC$</td>
</tr>
<tr>
<td>Non-commutativity</td><td>$AB \neq BA$</td>
</tr>
<tr>
<td>Associative property of multiplication</td><td>$(AB)C = A(BC)$</td>
</tr>
<tr>
<td>Multiplicative identity property</td><td>$IA = AI = A$</td>
</tr>
<tr>
<td></td><td>$A^{-1}A = AA^{-1} = I$
</td>
</tr>    
<tr>
<td></td><td>$(AB)^{-1} = B^{-1}A^{-1}$</td>
</tr>    
<tr>
<td>Reversivity of the transpose of a product of matrices,</td><td>$(AB)^T = B^TA^T$</td>
</tr>    
</table>

---