In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

In [4]:
ratings_values = np.random.randint(1, 100, (20,2))
ratings_columns = ['Price', 'Quality']
ratings = pd.DataFrame(ratings_values, columns=ratings_columns)
print(ratings_values)
print()
display(ratings)

[[ 5 34]
 [53 33]
 [43 60]
 [28 98]
 [73 90]
 [33 37]
 [17 29]
 [ 8 32]
 [29 70]
 [88 55]
 [63 61]
 [87 46]
 [57 59]
 [16 97]
 [50 46]
 [10  5]
 [50 78]
 [52 20]
 [44 61]
 [78 18]]



Price  Quality
0       5       34
1      53       33
2      43       60
3      28       98
4      73       90
5      33       37
6      17       29
7       8       32
8      29       70
9      88       55
10     63       61
11     87       46
12     57       59
13     16       97
14     50       46
15     10        5
16     50       78
17     52       20
18     44       61
19     78       18

In [5]:
price =  ratings['Price']
quality = ratings['Quality']

print('Price: ', price)
print('Quality: ', quality)

Price:  0      5
1     53
2     43
3     28
4     73
5     33
6     17
7      8
8     29
9     88
10    63
11    87
12    57
13    16
14    50
15    10
16    50
17    52
18    44
19    78
Name: Price, dtype: int32
Quality:  0     34
1     33
2     60
3     98
4     90
5     37
6     29
7     32
8     70
9     55
10    61
11    46
12    59
13    97
14    46
15     5
16    78
17    20
18    61
19    18
Name: Quality, dtype: int32


In [6]:
total_visitors = ratings.sum().sum()
total_visitors

1913

In [7]:
print('The mean of the price ratings: ', price.mean()) # < write your code here >
print('The median of the price ratings', price.median()) # < write your code here >

print('The mean of the quality ratings: ', quality.mean()) # < write your code here >
print('The median of the quality ratings', quality.median()) # < write your code here >

The mean of the price ratings:  44.2
The median of the price ratings 47.0
The mean of the quality ratings:  51.45
The median of the quality ratings 50.5


In [8]:
mean_ratings = ratings.mean(axis=1).round().astype(int) #axis=1 satir satir ele almak icin
mean_ratings

0     20
1     43
2     52
3     63
4     82
5     35
6     23
7     20
8     50
9     72
10    62
11    66
12    58
13    56
14    48
15     8
16    64
17    36
18    52
19    48
dtype: int32

In [9]:
new_ratings_values = np.column_stack((ratings_values, mean_ratings)) #colum stack kolanlari birlestir
print(new_ratings_values)
print(type(new_ratings_values))
print(new_ratings_values.shape)


[[ 5 34 20]
 [53 33 43]
 [43 60 52]
 [28 98 63]
 [73 90 82]
 [33 37 35]
 [17 29 23]
 [ 8 32 20]
 [29 70 50]
 [88 55 72]
 [63 61 62]
 [87 46 66]
 [57 59 58]
 [16 97 56]
 [50 46 48]
 [10  5  8]
 [50 78 64]
 [52 20 36]
 [44 61 52]
 [78 18 48]]
<class 'numpy.ndarray'>
(20, 3)


In [10]:
new_ratings = pd.DataFrame(new_ratings_values, columns=['Price', 'Quality', 'Average'])
display(new_ratings)

Price  Quality  Average
0       5       34       20
1      53       33       43
2      43       60       52
3      28       98       63
4      73       90       82
5      33       37       35
6      17       29       23
7       8       32       20
8      29       70       50
9      88       55       72
10     63       61       62
11     87       46       66
12     57       59       58
13     16       97       56
14     50       46       48
15     10        5        8
16     50       78       64
17     52       20       36
18     44       61       52
19     78       18       48

In [11]:
def mae(target, predictions):
    # < write your code here >
    return np.mean(np.abs(target-predictions)) #abs mutlak degeri 

In [12]:
target =  np.random.binomial(n=1, p=0.6, size=100) #p probability
predictions = np.ones(100, dtype=int)


print(target)
print()
print(predictions)

[1 1 0 1 1 1 1 1 0 1 0 1 1 0 1 1 1 0 1 1 1 0 0 0 1 0 0 0 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 1 0 1 0 1 1 1 0 1 1 0 0 1 0 1
 1 0 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 0 0 1 1 0 1 1 1 1]

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [13]:
mean_absolute_error =  mae(target, predictions)
mean_absolute_error

0.33

In [14]:
print(1-np.mean(target))

print(mean_absolute_error)

0.32999999999999996
0.33


In [ ]:
# Istatiksel bir gercek oldugunu dusunuyorum.