# NumPy Homework

# A

## 1) import numpy library with his usual alias!

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

## 2) Create a random matrix, which has 2 columns and 20 rows. With this we will then create a pandas DataFrame!

In [29]:
ratings_values = np.random.rand(20, 2)
ratings = pd.DataFrame(ratings_values, columns=['Rating1', 'Rating2'])
print(ratings_values)
print()
display(ratings)

[[0.85410833 0.83801849]
 [0.36270446 0.73023369]
 [0.51637093 0.5998843 ]
 [0.06124213 0.15598667]
 [0.90449834 0.779768  ]
 [0.62046569 0.59369415]
 [0.54731114 0.65856128]
 [0.81070732 0.7730383 ]
 [0.31679069 0.46770103]
 [0.33992112 0.78380544]
 [0.54032421 0.58811678]
 [0.75569309 0.86824685]
 [0.83239524 0.88863263]
 [0.02891568 0.46857195]
 [0.35359543 0.84266222]
 [0.28147345 0.90414011]
 [0.38495715 0.18405475]
 [0.07067337 0.87043351]
 [0.40113978 0.32391004]
 [0.87692673 0.6599933 ]]



Rating1   Rating2
0   0.854108  0.838018
1   0.362704  0.730234
2   0.516371  0.599884
3   0.061242  0.155987
4   0.904498  0.779768
5   0.620466  0.593694
6   0.547311  0.658561
7   0.810707  0.773038
8   0.316791  0.467701
9   0.339921  0.783805
10  0.540324  0.588117
11  0.755693  0.868247
12  0.832395  0.888633
13  0.028916  0.468572
14  0.353595  0.842662
15  0.281473  0.904140
16  0.384957  0.184055
17  0.070673  0.870434
18  0.401140  0.323910
19  0.876927  0.659993

## 3) Create two vectors from the previous DataFrame. We will use the same values from the previous DataFrame which we already have been created. The first one contains the evaluations which show the customer satisfaction for the prices, and the second one contains for the quality. How big how good! We will then print the vectors.

##### Hint: pd.DataFrame['column_name'] gives us a Series from a DataFrame. We can use it with the same functions as DataFrames.

In [30]:
price = ratings['Rating1']
quality = ratings['Rating2']

print('Price: ', price.to_list())
print('Quality: ', quality.to_list())

Price:  [0.8541083303849979, 0.3627044598688489, 0.5163709258606946, 0.06124213447770199, 0.9044983439148995, 0.6204656870816471, 0.5473111408276241, 0.8107073226533117, 0.3167906862944956, 0.3399211184969394, 0.5403242134989522, 0.7556930916282135, 0.8323952362892238, 0.028915680153785206, 0.3535954310239501, 0.2814734502051084, 0.3849571457076115, 0.07067337444566857, 0.40113977890343333, 0.8769267265171893]
Quality:  [0.8380184856689936, 0.7302336862561751, 0.5998843011033674, 0.15598667166483204, 0.7797680028867366, 0.5936941473811392, 0.6585612764050534, 0.7730383039187465, 0.46770103425949683, 0.7838054379851215, 0.5881167785116526, 0.8682468525198132, 0.8886326268831717, 0.46857195121314055, 0.842662219435325, 0.9041401142829262, 0.1840547522169672, 0.8704335061598222, 0.32391004474854945, 0.6599932966771843]


## 4) Find the total numbers of visitors.

In [31]:
total_visitors = len(ratings)

total_visitors

20

## 5) Find and print the average ratings for each column using numpy functions (we will find the mean and median values)

In [32]:
print('The mean of the price ratings: ', np.mean(price))
print('The median of the price ratings: ', np.median(price))

print('The mean of the quality ratings: ', np.mean(quality))
print('The median of the quality ratings: ', np.median(quality))


The mean of the price ratings:  0.49301071391171475
The median of the price ratings:  0.45875535238206394
The mean of the quality ratings:  0.6489726745089107
The median of the quality ratings:  0.6951134914666797


## 6) Create a new vector which is the average of the ratings of two columns, price and quality. We will name it as mean_ratings. It will show the average rating for each customer. Round elements of the array to the nearest integer.

In [33]:
mean_ratings = np.mean([price, quality], axis=0)
print(mean_ratings)
mean_ratings_rounded = np.round(mean_ratings)
print(mean_ratings_rounded)

[0.84606341 0.54646907 0.55812761 0.1086144  0.84213317 0.60707992
 0.60293621 0.79187281 0.39224586 0.56186328 0.5642205  0.81196997
 0.86051393 0.24874382 0.59812883 0.59280678 0.28450595 0.47055344
 0.36252491 0.76846001]
[1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1.]


## 7) Create ratings_values matrix again with the all three vectors. Average ratings, which has just been calculated in the previous exercise, should be the third column of the new matrix. All values in the matrix should be integer! New matrix should have 20 rows and 3 columns!

In [38]:
new_ratings_values = np.column_stack((price, quality, mean_ratings_rounded))
print(new_ratings_values)
print(type(new_ratings_values))
print(new_ratings_values.shape)


[[0.85410833 0.83801849 1.        ]
 [0.36270446 0.73023369 1.        ]
 [0.51637093 0.5998843  1.        ]
 [0.06124213 0.15598667 0.        ]
 [0.90449834 0.779768   1.        ]
 [0.62046569 0.59369415 1.        ]
 [0.54731114 0.65856128 1.        ]
 [0.81070732 0.7730383  1.        ]
 [0.31679069 0.46770103 0.        ]
 [0.33992112 0.78380544 1.        ]
 [0.54032421 0.58811678 1.        ]
 [0.75569309 0.86824685 1.        ]
 [0.83239524 0.88863263 1.        ]
 [0.02891568 0.46857195 0.        ]
 [0.35359543 0.84266222 1.        ]
 [0.28147345 0.90414011 1.        ]
 [0.38495715 0.18405475 0.        ]
 [0.07067337 0.87043351 0.        ]
 [0.40113978 0.32391004 0.        ]
 [0.87692673 0.6599933  1.        ]]
<class 'numpy.ndarray'>
(20, 3)


In [39]:
new_ratings = pd.DataFrame(new_ratings_values, columns=['Price', 'Quality', 'Average'])
display(new_ratings)

Price   Quality  Average
0   0.854108  0.838018      1.0
1   0.362704  0.730234      1.0
2   0.516371  0.599884      1.0
3   0.061242  0.155987      0.0
4   0.904498  0.779768      1.0
5   0.620466  0.593694      1.0
6   0.547311  0.658561      1.0
7   0.810707  0.773038      1.0
8   0.316791  0.467701      0.0
9   0.339921  0.783805      1.0
10  0.540324  0.588117      1.0
11  0.755693  0.868247      1.0
12  0.832395  0.888633      1.0
13  0.028916  0.468572      0.0
14  0.353595  0.842662      1.0
15  0.281473  0.904140      1.0
16  0.384957  0.184055      0.0
17  0.070673  0.870434      0.0
18  0.401140  0.323910      0.0
19  0.876927  0.659993      1.0

# B

## 1) Create *Mean Absolute Error (MAE)* function

\begin{equation}
MAE=\frac{1}{n}\sum_{i=1}^n|target_i - predictions_i|
\end{equation}

In [40]:
def mae(target, predictions):
    n = len(target)
    absolute_errors = np.abs(target - predictions)
    mae = np.sum(absolute_errors) / n
    return mae

## 2) Create two arrays each of them has $100$ observations. We will use them for *target* and *predictions* labelling. The target array should consist only $0$ or $1$ values which are random created, while predictions only integer $1$. The target array should have a *binomial distribution* which gives $1$ with $60$% probability.

In [43]:
target = np.random.binomial(1, 0.6, 100)
predictions = np.ones(100, dtype=int)

print("Target:", target)
print("\nPredictions:", predictions)

Target: [0 1 1 0 0 0 1 0 1 0 1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 0 0 1 0
 0 1 1 1 0 1 1 1 0 1 1 0 1 1 0 0 1 1 0 0 1 1 1 1 1 1 0 0 0 0 1 1 1 0 1 0 0
 1 0 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 0 1 1 0 1 1 0 0]

Predictions: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## 3) Find the *MAE* with your mae function

In [48]:
mean_absolute_error_result = mae(target, predictions)
print("mae =",mean_absolute_error_result)


mae = 0.48


## 4)  Run the code in this step. Observe the printed outputs. Try to run the codes a few times from step 2. What do you think about the results? Give your thoughts shortly with 3 - 5 sentences about why two outputs are the same. What is your conclusion?

In [51]:
print(1-np.mean(target))

print(mean_absolute_error_result)

0.48
0.48


### 1 - mean(target) calculates the average error of always predicting 1, which is what the MAE shows here. 

## 5) We have always chosen $1$ in our predictions, but the actual values at the target have changed each time. How likely is it that we got it right each time, and what determines this?

 ### < write your answer here >

# C

## 1) Create a Pythagorean function using *np.dot()* to calculate vector length

$$v = [x, y] ==> len_v = \sqrt{x^2+y^2}$$

In [52]:
def pythagorean_length(vector):
    len_v = np.sqrt(np.dot(vector, vector))
    return len_v

## 2) Calculate the length of the given vector using your *pythagorean_length* function and check your result comparing with the given

In [53]:
a = np.array([3, 4])

length_of_a = pythagorean_length(a)
print("Length of the vector:", length_of_a)

Length of the vector: 5.0


## 3) Find the shortest distance (Euclidean distance) using *np.dot()* between the given two vectors and compare the results to check

In [55]:
a = np.array([5, 6])
b = np.array([1, 3])

c = np.sqrt(np.dot(a - b, a - b))
print('The distance between a and b is', c)

from scipy.spatial import distance
print('The distance between a and b should be', distance.euclidean(a, b))

The distance between a and b is 5.0


The distance between a and b should be 5.0


# D - Obfuscating Data

It is best to obfuscate data by multiplying the numerical features (they can be seen as the matrix $X$) by an invertible matrix $P$. 

$$
X' = X \times P
$$

Try to do that and check how the features' values will look like after the transformation. By the way, the invertible property is important here so make sure that $P$ is indeed invertible.

## 1) Protect customers' personal data. It is necessary to develop a data transformation algorithm that makes it difficult to recover personal information in case the data falls into the wrong hands. This is called data masking or data obfuscation. However, the data must be protected in such a way that the quality of the machine learning models does not suffer. You don't need to choose the best model, just prove that the algorithm works correctly.

In [56]:
# pd.DataFrame
columns = ['gender', 'age', 'salary', 'family_members']
data = np.array([np.random.choice([0, 1], size=1000), 
                 np.random.randint(18, 100, 1000), 
                 np.random.normal(25000, 5000, 1000).astype(int), 
                 np.random.randint(0, 10, 1000)
                ])

personal_data = pd.DataFrame(data.T, columns=columns)
display(personal_data.tail(10))

gender  age  salary  family_members
990       1   68   24306               8
991       1   83   25080               2
992       0   91   19417               8
993       0   78   20338               0
994       0   85   31898               3
995       0   89   27971               4
996       1   29   29693               5
997       1   66   20966               8
998       0   53   23964               1
999       1   55   26352               6

In [ ]:
# < write your code here > 



In [58]:
# < write your code here > a rondom generated square matrix
transformation_matrix = np.random.rand(3, 3) 
transformation_matrix

array([[0.57668552, 0.21303828, 0.34297212],
       [0.56605946, 0.93250481, 0.57515572],
       [0.63365408, 0.96394699, 0.94150596]])

**(Hint:** https://numpy.org/doc/stable/reference/random/generator.html **)**

In [ ]:
 # < write your code here > This is our new crypted datas.

In [ ]:
# < write your code here > 

## 2) Can you guess the customers' ages or income after the transformation?

In [ ]:
# Secure Data
pd.DataFrame(<............>).describe() # < write your code here >

#### write your conlusion here

## 3) Can you recover the original data from $X'$ if you know $P$? Try to check that with calculations by moving $P$ from the right side of the formula above to the left one. The rules of matrix multiplication are helpful here.

In [ ]:
# < write your code here >

In [ ]:
# Printing all three cases for a few customers


In [ ]:
# Original Data
personal_data.tail(10)

In [ ]:
# Secure Data
pd.DataFrame("<............>").tail(10)  # < write your code here >

In [ ]:
# Recovered Data
pd.set_option('display.float_format', '{:.2f}'.format)
pd.DataFrame(<............>).astype('int').tail(10) # < write your code here >

#### write your conlusion here

---

# USEFUL INFORMATIONS

##### Matrices and Matrix Operations

- **A matrix** is a rectangular numeric table or two-dimensional array consisting of m rows and n columns.
- **A transpose of the matrix** is a matrix operation when its rows become columns with the same numbers.- **Dummy code** is a simple code that doesn't mean anything.
- **An identity matrix** is a square matrix with ones on the main diagonal and zeros elsewhere.
- **An inverse matrix** for a square matrix A is a matrix A with a superscript -1 whose product with A is equal to the identity matrix.
- **Invertible matrices** are matrices that have an inverse.
- **Non-invertible** are matrices that don't have an inverse.

# Properties of Matrices

Matrices have many properties in Linear Algebra.

<table>
<tr>
<td>Distributivity</td><td>$A(B+C)=AB+AC$</td>
</tr>
<tr>
<td>Non-commutativity</td><td>$AB \neq BA$</td>
</tr>
<tr>
<td>Associative property of multiplication</td><td>$(AB)C = A(BC)$</td>
</tr>
<tr>
<td>Multiplicative identity property</td><td>$IA = AI = A$</td>
</tr>
<tr>
<td></td><td>$A^{-1}A = AA^{-1} = I$
</td>
</tr>    
<tr>
<td></td><td>$(AB)^{-1} = B^{-1}A^{-1}$</td>
</tr>    
<tr>
<td>Reversivity of the transpose of a product of matrices,</td><td>$(AB)^T = B^TA^T$</td>
</tr>    
</table>

---