In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

In [3]:
random_matrix=np.random.rand(20,2)
df=pd.DataFrame(random_matrix,columns=['price','quality'])


In [4]:
price_vector=df['price']
quality_vector=df['quality']
print('Price: ', price_vector)
print('Quality: ', quality_vector)

Price:  0     0.117826
1     0.999640
2     0.992828
3     0.233316
4     0.810034
5     0.097997
6     0.144344
7     0.182973
8     0.387504
9     0.699287
10    0.854941
11    0.250380
12    0.065056
13    0.311799
14    0.223021
15    0.222261
16    0.848893
17    0.419662
18    0.249407
19    0.396780
Name: price, dtype: float64
Quality:  0     0.953185
1     0.081447
2     0.768040
3     0.342827
4     0.325330
5     0.929723
6     0.302517
7     0.183077
8     0.170004
9     0.433040
10    0.412943
11    0.148165
12    0.733413
13    0.903770
14    0.403760
15    0.700997
16    0.910520
17    0.831492
18    0.284742
19    0.706428
Name: quality, dtype: float64


In [5]:
print(df['price'].sum())
print(df['quality'].sum())

8.507949688285418
10.525419674797119


In [6]:
print('The mean of the price ratings: ',df['price'].mean()) 
print('The median of the price ratings', df['price'].median() ) 

print('The mean of the quality ratings: ', df['quality'].mean())
print('The median of the quality ratings', df['quality'].median()) 

The mean of the price ratings:  0.4253974844142709
The median of the price ratings 0.28108936986169575
The mean of the quality ratings:  0.5262709837398559
The median of the quality ratings 0.42299135974721364


In [7]:
mean_ratings = df[['price','quality']].median(axis=1).round()
print(mean_ratings)

0     1.0
1     1.0
2     1.0
3     0.0
4     1.0
5     1.0
6     0.0
7     0.0
8     0.0
9     1.0
10    1.0
11    0.0
12    0.0
13    1.0
14    0.0
15    0.0
16    1.0
17    1.0
18    0.0
19    1.0
dtype: float64


6) Mean Ratings

In [8]:
new_ratings_values = np.column_stack((price_vector, quality_vector, mean_ratings))
new_ratings_values.astype(int)
new_ratings = pd.DataFrame(new_ratings_values, columns=['Price', 'Quality', 'Average'])
print(new_ratings)

       Price   Quality  Average
0   0.117826  0.953185      1.0
1   0.999640  0.081447      1.0
2   0.992828  0.768040      1.0
3   0.233316  0.342827      0.0
4   0.810034  0.325330      1.0
5   0.097997  0.929723      1.0
6   0.144344  0.302517      0.0
7   0.182973  0.183077      0.0
8   0.387504  0.170004      0.0
9   0.699287  0.433040      1.0
10  0.854941  0.412943      1.0
11  0.250380  0.148165      0.0
12  0.065056  0.733413      0.0
13  0.311799  0.903770      1.0
14  0.223021  0.403760      0.0
15  0.222261  0.700997      0.0
16  0.848893  0.910520      1.0
17  0.419662  0.831492      1.0
18  0.249407  0.284742      0.0
19  0.396780  0.706428      1.0


7)

In [11]:
new_ratings_values = np.column_stack((price_vector, quality_vector, mean_ratings))
new_ratings_values = new_ratings_values.astype(int)
print(new_ratings_values)
print(type(new_ratings_values))
print(new_ratings_values.shape)



[[0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 0]
 [0 0 1]]
<class 'numpy.ndarray'>
(20, 3)


In [12]:
new_ratings_data =pd.DataFrame(new_ratings_values, columns=['Price', 'Quality', 'Average'])
display(new_ratings_data)

Price  Quality  Average
0       0        0        1
1       0        0        1
2       0        0        1
3       0        0        0
4       0        0        1
5       0        0        1
6       0        0        0
7       0        0        0
8       0        0        0
9       0        0        1
10      0        0        1
11      0        0        0
12      0        0        0
13      0        0        1
14      0        0        0
15      0        0        0
16      0        0        1
17      0        0        1
18      0        0        0
19      0        0        1

In [13]:
def mae(target, predictions):
    target = np.array(target)
    predictions = np.array(predictions)
    
    
    mae = np.mean(np.abs(target - predictions))
    
    return mae
print(mae(price_vector,quality_vector))

0.3664381787539791


In [22]:
target_array = np.random.binomial(n=1, p=0.6, size=100)
predictions_array = np.ones(100, dtype=int)

print(target_array)

print(predictions_array)

[0 1 1 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 1 0 0 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 0 0 1 0 1 0 1 0 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 1 0 1 1 1
 0 0 1 0 0 0 1 1 1 0 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 1]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [23]:
mean_absolute_error =  mae(target_array,predictions_array)
mean_absolute_error

0.43

Random sequences varied with each application, which changed the outcome

In [26]:
def pythagorean(vector):
        
    dot_product = np.dot(vector, vector)
    length = np.sqrt(dot_product)
    
    return length


vector = np.array([5, 6])  
length = pythagorean(vector)
print("Length of the vector:", length)

Length of the vector: 7.810249675906654


In [25]:
a = np.array([3, 4])
length_av =pythagorean(a)
print(length_av)

5.0


In [29]:
from scipy.spatial import distance
a = np.array([5, 6])
b = np.array([1, 3])

c = np.sqrt(np.dot(a - b, a - b))
print('The distance is', c)
print('The distance should be', distance.euclidean(a, b))

The distance is 5.0
The distance should be 5.0


In [30]:
columns = ['gender', 'age', 'salary', 'family_members']
data = np.array([np.random.choice([0, 1], size=1000), 
                 np.random.randint(18, 100, 1000), 
                 np.random.normal(25000, 5000, 1000).astype(int), 
                 np.random.randint(0, 10, 1000)
                ])

personal_data = pd.DataFrame(data.T, columns=columns)
display(personal_data.tail(10))

gender  age  salary  family_members
990       0   87   26896               6
991       0   76   22540               0
992       0   62   23369               6
993       0   84   29496               1
994       1   30   27503               2
995       0   64   27916               1
996       0   55   22966               8
997       0   94   25553               5
998       0   45   28499               9
999       0   80   27323               4